name: test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
      - run: npm i esbuild typescript --legacy-peer-deps
      - run: npm run build
      - run: npm test
